### PR TITLE
Add readme FR and suggestion

### PR DESCRIPTION
**Pull request by bettydreemurr**

### CODE REVIEW

**Comment by carcaschoi** [comment]
the last three only?

**Comment by bettydreemurr** [comment]
All the modifications, it's just that I had to import all the source code into my project with another branch, that's why there are so many messages and excuse me for not to have answered attentively because I have exams in this moment haha x)

**Comment by carcaschoi** [comment]
Well，you can notice me if you are ok😁

**Comment by carcaschoi** [comment]
I don't want to merge your old stuff. Would you like to pull a new request😅

**Pull request closed without merging**
